### ISSUE TITLE
Can't use it with Vuetify?

### ISSUE THREAD

**Issue by MuhaddiMu** [apertureless/vue-parallax#41]
I want to use it with Vuetify as Vuetify parallax doesn't allow so many options. Using vue-parallax inside Vuetify breaks things and doesn't work as expected. 

Any help would be highly valued

**Comment by apertureless** [comment]
What do you mean with, it breaks ? 
Can you maybe provide a small codepen for reproduction?

**Comment by MuhaddiMu** [comment]
@apertureless  Thank you for your response. 

Here is the code sandbox, https://codesandbox.io/s/vuetify-playground-gd9lf

By breaking, I mean that the `<parallax>` content is not showing up. It's just showing a blank screen. It looks like Vuetify is overriding the styles. Any possible fix to this?

**Comment by apertureless** [comment]
Thanks for the sandbox.
It seems to be an css (z-index) issue.
Because your container is overlapping everything.

If you add 

```css
position: realtive;
z-index: 0
```

to your container class, it is fixed.

The parallax effect relys currently heavily on css styling. So it can often come to problems.

![Bildschirmfoto 2019-11-21 um 12 27 31](https://user-images.githubusercontent.com/4975917/69334212-8a979000-0c5a-11ea-977f-6cc69a1854a0.png)
